#!/bin/bash

# Output file is passed as first argument
OUTPUT=$1

# Function to generate assembly stubs
generate_asm() {
    echo "; !!! THIS FILE IS AUTOGENERATED !!!" > "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    # Macro for ISRs without error code
    echo "%macro ISR_NOERRCODE 1" >> "$OUTPUT"
    echo "    global x86_64_ISR%1" >> "$OUTPUT"
    echo "    x86_64_ISR%1:" >> "$OUTPUT"
    echo "        cli" >> "$OUTPUT"
    echo "        push 0" >> "$OUTPUT"
    echo "        push %1" >> "$OUTPUT"
    echo "        jmp isr_common_stub" >> "$OUTPUT"
    echo "%endmacro" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # Macro for ISRs with error code
    echo "%macro ISR_ERRCODE 1" >> "$OUTPUT"
    echo "    global x86_64_ISR%1" >> "$OUTPUT"
    echo "    x86_64_ISR%1:" >> "$OUTPUT"
    echo "        cli" >> "$OUTPUT"
    echo "        push %1" >> "$OUTPUT"
    echo "        jmp isr_common_stub" >> "$OUTPUT"
    echo "%endmacro" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    for i in $(seq 0 255); do
        # Exceptions with error codes
        if [ "$i" -eq 8 ] || [ "$i" -eq 10 ] || [ "$i" -eq 11 ] || [ "$i" -eq 12 ] || \
           [ "$i" -eq 13 ] || [ "$i" -eq 14 ] || [ "$i" -eq 17 ] || [ "$i" -eq 21 ] || \
           [ "$i" -eq 29 ] || [ "$i" -eq 30 ]; then
            echo "ISR_ERRCODE $i" >> "$OUTPUT"
        else
            echo "ISR_NOERRCODE $i" >> "$OUTPUT"
        fi
    done
}

# Function to generate C initialization code
generate_c() {
    echo "// !!! THIS FILE IS AUTOGENERATED !!!" > "$OUTPUT"
    echo "#include \"idt.h\"" >> "$OUTPUT"
    echo "#include \"gdt.h\"" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    # Declarations
    for i in $(seq 0 255); do
        echo "void x86_64_ISR$i();" >> "$OUTPUT"
    done

    echo "" >> "$OUTPUT"
    echo "void x86_64_ISR_InitializeGates()" >> "$OUTPUT"
    echo "{" >> "$OUTPUT"

    # Initialization
    for i in $(seq 0 255); do
        echo "    x86_64_IDT_SetGate($i, x86_64_ISR$i, X86_64_GDT_CODE_SEGMENT, IDT_FLAG_RING0 | IDT_FLAG_GATE_64BIT_INT);" >> "$OUTPUT"
    done

    echo "}" >> "$OUTPUT"
}

# Check extension
if [[ "$OUTPUT" == *".inc" ]]; then
    generate_asm
elif [[ "$OUTPUT" == *".c" ]]; then
    generate_c
else
    echo "Unknown file type: $OUTPUT"
    exit 1
fi